name: Continuous Delivery - HUD LUA

on:
  release:
    types: [published]

env:
  PROJECT: "hud"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Bundle  
      shell: pwsh
      run: |
        $excludeDirs = @('.github','.vscode','definitions', 'knightlinc')
        $releaseDir = $env:PROJECT + "\"
        $Directories = Get-ChildItem -Directory "." -Exclude $excludeDirs 

        function CopyReleaseContents($parentDir, $directories) {
          foreach($dir in $directories) {
            $currentDir = ($parentDir + $dir.Name + "\")
            $childReleaseDir = ($releaseDir + $currentDir)
            New-Item -Path $childReleaseDir -ItemType Directory
            Copy ($currentDir + "*.lua") $childReleaseDir 


            $ChildDirectories = Get-ChildItem -Directory $currentDir 
            CopyReleaseContents ($currentDir+"\") $ChildDirectories
          }
        }

        New-Item -Path $releaseDir -ItemType Directory
        Copy "*.lua" $releaseDir
        CopyReleaseContents '.\' $Directories

        function CopyLib($libDirectory) {
            New-Item -Path ($releaseDir + "/" + $libDirectory)  -ItemType Directory
            Copy ($libDirectory + "/*.lua") ($releaseDir + "/" + $libDirectory) 
        }

        CopyLib("knightlinc")

        7z a -tzip $env:PROJECT_${{ github.ref_name }}.zip -r ($env:PROJECT + "/*.lua")

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: hud_${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/easy-zip-files        